name: ToughAsNailsU
version: '${project.version}'
main: me.udnek.toughasnailsu.ToughAsNailsU
api-version: '1.21.4'
depend: [ItemsCoreU]
softdepend: [RpgU]
commands:
  tanudebug:
    description: "tanudebug"
    usage: "/tanudebug"
    aliases: []
    permission: tanu.admin
    permission-message: "You do not have permission to use this command"