name: ToughAsNailsU
version: '${project.version}'
main: me.udnek.toughasnailsu.ToughAsNailsU
api-version: '1.21.1'
depend: [ItemsCoreU]
commands:
  tanudebug:
    description: "tanudebug"
    usage: "/tanudebug"
    aliases: []
    permission: tanu.admin
    permission-message: "You do not have permission to use this command"
  testcommand:
    description: "testcommand"
    usage: "/testcommand"
    aliases: [ ]
    permission: tanu.admin
    permission-message: "You do not have permission to use this command"